apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    name: hello-world
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/data/metrics'
    prometheus.io/port: '80'
spec:
  replicas: 2
  selector:
    matchLabels:
      name: hello-world
  template:
    metadata:
      name: hello-world
      labels:
        name: hello-world
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/data/metrics'
        prometheus.io/port: '80'
    spec:
      containers:
        - name: hello-world
          image: hello-world:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: hello-world
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: hello-world