server:
  port: 80
management.endpoints.web.exposure.include: 'prometheus'
management.endpoint.health.show-details: always
management:
  endpoints:
    web:
      base-path: /hello
      path-mapping:
        prometheus: metrics